"""rpg_dsl — RPG-OP declarative spec DSL."""

from ._decorators import (
    DELETE,
    GET,
    PATCH,
    POST,
    PUT,
    Canvas,
    Eval,
    Field,
    Presentation,
    Region,
    Sheet,
    SubAgent,
    api,
    assert_contains,
    assert_not_contains,
    assert_tool_called,
    sheet_field,
)
from ._models import (
    ApiSpec,
    CanvasSpec,
    EvalAssertion,
    EvalSpec,
    FieldSpec,
    PresentationType,
    RegionSpec,
    RouteSpec,
    SheetSpec,
    SubAgentSpec,
)
from ._registry import all_specs, clear, get_all, register

__all__ = [
    "DELETE",
    "GET",
    "PATCH",
    "POST",
    "PUT",
    # IR models
    "ApiSpec",
    # Decorators
    "Canvas",
    "CanvasSpec",
    "Eval",
    "EvalAssertion",
    "EvalSpec",
    "Field",
    "FieldSpec",
    "Presentation",
    "PresentationType",
    "Region",
    "RegionSpec",
    "RouteSpec",
    "Sheet",
    "SheetSpec",
    "SubAgent",
    "SubAgentSpec",
    # Registry
    "all_specs",
    "api",
    "assert_contains",
    "assert_not_contains",
    "assert_tool_called",
    "clear",
    "get_all",
    "register",
    "sheet_field",
]
